#%RAML 1.0 DataType

additionalProperties: false
properties:
  bi:
    type: string
    displayName: Bodily Injury
  col:
    type: string
    displayName: Collision
  comp:
    type: string
    displayName: Comprehensive
  med:
    type: string
    displayName: Medical Payments
  pd: 
    type: string
    displayName: Property Damage
  rerim:
    type: string
    displayName: Rental Reimbursement
  premium: 
    type: string
    displayName: Premium
  quoteId:
    type: string
    displayName: QuoteId
  status:
    type: string
    displayName: Underwriter Decision
  id:
    type: string
    displayName: covergaeId