#%RAML 1.0
title: rate-api
version: 1.0.0
mediaType: 
- application/json
traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
types:
  rateRequest: !include rateRequest.raml
  rateResponse: !include rateResponse.raml
  healthcheck: !include healthcheck.raml
  getRateQuoteResponse: !include getRateQuoteResponse.raml
  apiErrorResponse: !include apiErrorResponse.raml

/live:
  get:
    displayName: used to check liveness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
            example: | 
              {
                "status" : "application live!!!",
                "checks": 
                [
                  "Container",
                  "Cache"
                ]
              }
/ready:
  get:
    displayName: used to check readiness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
            example: | 
              {
                "status" : "application ready!!!",
                "checks": 
                [
                  "Content",
                  "DataBase"
                ]
              }
/health:
  get:
    displayName: combined health (liveness & readiness) check 
    responses:
      200:
        body:
          application/json:
            type: healthcheck
            example: | 
              {
                "status" : "application healthy!!!",
                "checks": 
                [
                  "CacheService",
                  "Database Connector",
                  "MQ"
                ]
              }
/api/rate/{quoteId}:
  get:
    responses:
      200:
        body:
          application/json:
            type: getRateQuoteResponse
            example: !include getRateQuoteResponseExample.json
      400:
        body:
          application/json:
            type: apiErrorResponse
            example: !include badRequestResponse.json
      401:
        body:
          application/json:
            type: apiErrorResponse
            example: !include unauthorizedErrorResponse.json
      500:
        body:
          application/json:
            type: apiErrorResponse
            example: !include internalServerErrorResponse.json
  post:
    body:
      application/json:
        type: rateRequest
    responses:
      200:
        body:
          application/json:
            type: rateResponse
            example: !include rateResponseExample.json
      400:
        body:
          application/json:
            type: apiErrorResponse
            example: !include badRequestResponse.json
      401:
        body:
          application/json:
            type: apiErrorResponse
            example: !include unauthorizedErrorResponse.json
      500:
        body:
          application/json:
            type: apiErrorResponse
            example: !include internalServerErrorResponse.json
  delete:
    responses:
      200:
        body:
          application/json:
            type: object
            example: | 
              {"status" : "Operation Successful"}
      400:
        body:
          application/json:
            type: apiErrorResponse
            example: !include badRequestResponse.json
      401:
        body:
          application/json:
            type: apiErrorResponse
            example: !include unauthorizedErrorResponse.json
      500:
        body:
          application/json:
            type: apiErrorResponse
            example: !include internalServerErrorResponse.json
